services:

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  krishisetu:
    build: .

    container_name: krishi-app

    ports:
      - "5000:5000"

    environment:
      MONGODB_URI: mongodb://mongodb:27017/krishisetu
      SESSION_SECRET: production-secret

    depends_on:
      - mongodb

volumes:
  mongodb_data:
